version: '3.8'

services:
  promptwire:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: promptwire-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # Mount for persistent storage (if needed)
      - promptwire_data:/app/data

volumes:
  promptwire_data:
    # Named volume for persistent data
