name: Continuous Delivery Pipeline For Server

on:
  push:
    branches:
      - main
    paths:
      - 'app/server/**'
  workflow_dispatch:

jobs:
  ci-cd:
    name: Continuous Delivery for Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Switch to main branch
        run: |
          git checkout main
          git pull origin main
        if: success()

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: success()

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
        if: success()

      - name: Build and Push Docker Image To HCR
        run: |
          docker build -t registry.heroku.com/mlops-final-project-server/web .
          docker push registry.heroku.com/mlops-final-project-server/web
        working-directory: ./app/server
        if: success()

      - name: Release the Container
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release web --app mlops-final-project-server
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        if: success()